package ShipmentTypes

object ErrorCodes {
    const val EXPRESS_DELIVERY_TOO_LATE = "EXPRESS_DELIVERY_TOO_LATE"
    const val OVERNIGHT_DELIVERY_INVALID = "OVERNIGHT_DELIVERY_INVALID"
    const val BULK_DELIVERY_TOO_SOON = "BULK_DELIVERY_TOO_SOON"
}